### ISSUE TITLE
Implement hot spots into the images

### ISSUE THREAD

**Issue by KarolinaNK** [NorthKingdom/alone-in-space#3]

**Comment by mklasinc** [comment]
the dummy hotspots are in place, once i receive the design assets i will do the replacements

**Comment by KarolinaNK** [comment]
@mklasinc updated hotspots placements (updated design will be ready by Monday)
https://www.dropbox.com/s/vk1mkaheosh29kq/360%20Hot%20Spot%20markings%20ver%202.pdf?dl=0
